name: wayne_music
description: A modern local music player.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture & State
  provider: ^6.1.1

  # Audio Core
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.11
  on_audio_query: 2.9.0 # Reverted to stable 2.9.0 with targeted Gradle fix

  # Permissions & System
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  http: ^1.2.0
  audio_session: ^0.1.21
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.5

  # UI & Utility
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true